import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Mobile Developer",
    company: "Pt. Universal Big Data (UBIG)",
    logo: "/images/careers/ubig.png",
    location: "Malang, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2024-12",
    end_date: "2025-12",
    industry: "Software Development & Technology Services",
    link: "https://ubig.co.id/",
    responsibilities: [
      "Developed and launched the \"eSchool Guru & Staff\" mobile application, now available on the Google Play Store, to support teachers and staff in managing academic and administrative tasks.",
      "Worked as a solo developer, handling the complete development cycle from system design, coding, testing, to deployment.",
      "Published and maintained the app on Google Play Store, delivering updates and improvements based on user needs.",
    ],
    isShow: true,
  },
  {
    position: "Mobile & Backend Developer",
    company: "PaperPlay Studio",
    logo: "/images/careers/paperplay.png",
    location: "Malang, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2024-05",
    end_date: "2024-11",
    industry: "Software Development & Technology Services",
    link: "https://www.paperplay.id/",
    responsibilities: [
      "--- Backend Development Projects ---",
      "Developed backend functionalities using Laravel to power the \"Wedvite\" digital wedding invitation platform.",
      "Collaborated with frontend developers to design and deliver seamless integration between backend services and user interfaces.",
      "Contributed as part of the backend team, focusing on optimizing workflows and maintaining code quality standards.",
      "--- Mobile Development Projects ---",
      "Designed and developed the mobile application \"Kibiyu,\" an interactive educational app bringing the inspiring story of Prophet Yusuf AS to life.",
      "Built engaging storytelling features, including audio narration and illustrated storylines, to enhance the learning experience.",
      "Delivered a smooth and user-friendly interface that allows users to explore lessons of patience, honesty, and wisdom through interactive content.",
    ],
    isShow: true,
  },
];
